# Generic ESP32 with 8MB Flash + 2MB PSRAM Board Configuration

set(MICROPY_BOARD "ESP32_GENERIC_8MB_2MB")

# Enable PSRAM support
set(CONFIG_SPIRAM_SUPPORT ON)
set(CONFIG_SPIRAM_USE ON)
set(CONFIG_SPIRAM_TYPE_ESPPSRAM32 ON)
set(CONFIG_SPIRAM_SIZE 2)

# Flash configuration for 8MB
set(CONFIG_ESPTOOLPY_FLASHSIZE_8MB ON)
set(CONFIG_ESPTOOLPY_FLASHSIZE "8MB")

# Partition table for larger flash
set(CONFIG_PARTITION_TABLE_CUSTOM ON)
set(CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions-8MB.csv")

# TWAI/CAN support
set(CONFIG_TWAI_SUPPORT ON)
